#!/usr/bin/env python2.2

import sys
import novelwriting.gram as gram
import novelwriting.tb

if len(sys.argv) == 1:
    f = sys.stdin
    fn = "<stdin>"
else:
    f = open(sys.argv[1])
    fn = sys.argv[1]

prog = f.read()
parts = prog.split("\n;;\n")

if len(parts) > 1:
    code = "\n" * parts[0].count("\n") + parts[1]
    code = compile(code, fn, "exec")
    exec code
gram.parse("start", parts[0] + "\n;;\n")

f.close()
